server:
  port: 8083

spring:
  sql:
    init:
      mode: always
  r2dbc:
    url: r2dbc:postgresql://${DB_IP}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}


jwt:
  password:
    encoder:
      secret: ${PASS_SECRET}
      iteration: 64
      keylength: 256
  secret: ${TOKEN_SECRET}
  expiration: ${TOKEN_EXPIRATION}
  issuer: nikitos




